### ISSUE TITLE
Mod not working with latest version of Beat Saber

### ISSUE THREAD

**Issue by PhreddoFrog** [D3rPole/BS-LightToSerial#7]
On the latest version of beat saber the mod crashes my game and freaks out my crash logs, and constantly causes the game not to work until I uninstall the mod. It worked fine pre achievements update

**Comment by D3rPole** [comment]
Are you using the latest version? The mod works fine with the letest beatsaber version.

**Comment by PhreddoFrog** [comment]
Works now, however performance is significantly reduced when using the mod
